# Generated by Django 4.2.1 on 2023-05-19 00:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Udm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udm', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde', models.IntegerField()),
                ('obse', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('unid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.udm')),
            ],
        ),
    ]
